# Your Name or Company
title: Marybeth & Josh Are Getting Married!

# Description of your website. This is used for social sharing.
description:  Marybeth Kram and Josh Beckman will be getting married September 19th 2020.

# A brief blurb about yourself
content: After ten years, Marybeth and Josh will be getting married September 19th, 2020!

# Add your social links
social:
  - platform: More Coming Soon
    url: ''
twitter: _andjosh

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: half-lg.jpg

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
