# Your Name or Company
title: Marybeth & Josh Are Getting Married!

# Description of your website. This is used for social sharing.
description:  Marybeth Kram and Josh Beckman will be getting married September 19th 2020.

# A brief blurb about yourself
content: Nullam id dolor id nibh ultricies vehicula ut id elit. Cras mattis consectetur purus sit amet fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum.

# Add your social links
social:
  - platform: github
    url: https://github.com/andjosh
  - platform: facebook
    url: https://facebook.com/andjosh
  - platform: twitter
    url: https://twitter.com/_andjosh
  - platform: linkedin
    url: andjosh

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: half-lg.jpg
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
